version: 2.1
orbs:
  node: circleci/node@5.0.0
workflows:
  build-and-deploy:
    jobs:
      - node/run:
          name: Validate Build
          npm-run: build -- --noEmit
      - node/run:
          name: Lint
          npm-run: lint
      - node/test:
          matrix:
            alias: Run Tests
            parameters:
              version:
                - "12.22"
                - "14.19"
                - "16.13"
                - "lts"
          requires: ["Validate Build", "Lint"]
      - node/run:
          name: Release
          requires: ["Validate Build", "Lint", "Run Tests"]
          npm-run: release
          context: npm
          filters:
            branches:
              only: main
